/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description This week's bounded set — ranked items first, the visible exclusion
         *     at the queue's end (Doc 06 §7). An empty week is an honest week.
         */
        get: operations["get_queue_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/{recommendation_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Decision */
        post: operations["record_decision_v1_recommendations__recommendation_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Correction */
        post: operations["apply_correction_v1_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prospects/{prospect_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Outcome */
        post: operations["record_outcome_v1_prospects__prospect_id__outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dna/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_v1_dna_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dna/proposals/{proposal_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Proposal */
        post: operations["decide_proposal_v1_dna_proposals__proposal_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prospects/{prospect_id}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Delivered Brief */
        get: operations["get_delivered_brief_v1_prospects__prospect_id__brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interview State */
        get: operations["interview_state_v1_interview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interview/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Interview Answer */
        post: operations["record_interview_answer_v1_interview_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dna */
        get: operations["get_dna_v1_dna_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dna/endorse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Endorse Dna
         * @description The C2 endorsement moment: the customer converts Xenia's model into a
         *     shared agreement (Doc 03 §3).
         */
        post: operations["endorse_dna_v1_dna_endorse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dna/document.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Dna Document */
        get: operations["export_dna_document_v1_dna_document_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prospects/{prospect_id}/brief.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Brief Pdf
         * @description The shareable artefact — approved briefs only (the Editor gate is the
         *     only door, Doc 10 Epic 9).
         */
        get: operations["export_brief_pdf_v1_prospects__prospect_id__brief_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prospects/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Prospects Csv
         * @description Lifecycle export: business names and statuses. No contacts exist in
         *     this system to export, and none ever will (Foundation N1).
         */
        get: operations["export_prospects_csv_v1_prospects_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Billing */
        get: operations["get_billing_v1_billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prospects/{prospect_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_v1_prospects__prospect_id__draft_get"];
        /**
         * Edit Draft
         * @description Always-editable: the founder's edit is the final word (and a voice
         *     signal for later — recorded by the save, judged by nobody).
         */
        put: operations["edit_draft_v1_prospects__prospect_id__draft_put"];
        /** Compose Draft */
        post: operations["compose_draft_v1_prospects__prospect_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /** Question Key */
            question_key: string;
            /** Text */
            text: string;
        };
        /** BillingResponse */
        BillingResponse: {
            /** Subscription Status */
            subscription_status: string;
            /** Payment Link Url */
            payment_link_url: string | null;
            /** Portal Url */
            portal_url: string | null;
        };
        /** BriefSectionResponse */
        BriefSectionResponse: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Cited Evidence Ids */
            cited_evidence_ids: string[];
        };
        /** ChangelogEntryResponse */
        ChangelogEntryResponse: {
            /** Cause */
            cause: string;
            /** Author */
            author: string;
            /** Element Statement */
            element_statement: string | null;
            /** Occurred At */
            occurred_at: string;
        };
        /** CorrectionRequest */
        CorrectionRequest: {
            target_kind: components["schemas"]["CorrectionTargetKind"];
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Reason */
            reason?: string | null;
        };
        /** CorrectionResponse */
        CorrectionResponse: {
            /**
             * Correction Id
             * Format: uuid
             */
            correction_id: string;
            /** Effect Summary */
            effect_summary: string;
            /** Removed Prospect Ids */
            removed_prospect_ids: string[];
            /** Added Prospect Ids */
            added_prospect_ids: string[];
            /** Reranked Count */
            reranked_count: number;
        };
        /**
         * CorrectionTargetKind
         * @enum {string}
         */
        CorrectionTargetKind: "evidence_item" | "score_factor" | "dna_element";
        /**
         * DecisionKind
         * @enum {string}
         */
        DecisionKind: "accept" | "decline" | "pursue";
        /** DecisionRequest */
        DecisionRequest: {
            kind: components["schemas"]["DecisionKind"];
            chip?: components["schemas"]["DeclineChip"] | null;
            /** Reason */
            reason?: string | null;
        };
        /** DecisionResponse */
        DecisionResponse: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            kind: components["schemas"]["DecisionKind"];
            /** Lesson */
            lesson: string | null;
        };
        /**
         * DeclineChip
         * @description The reason chips, verbatim from Doc 06 §6 — the chips *are* the
         *     teaching vocabulary.
         * @enum {string}
         */
        DeclineChip: "wrong_industry" | "too_small" | "bad_timing" | "we_know_them" | "evidence_is_wrong" | "not_our_kind_of_client";
        /** DeliveredBriefResponse */
        DeliveredBriefResponse: {
            /**
             * Brief Id
             * Format: uuid
             */
            brief_id: string;
            /**
             * Prospect Id
             * Format: uuid
             */
            prospect_id: string;
            /** Sections */
            sections: components["schemas"]["BriefSectionResponse"][];
            /** Couldnt See */
            couldnt_see: string[];
            /** Confidence Word */
            confidence_word: string;
            /** Receipts */
            receipts: components["schemas"]["ReceiptResponse"][];
            /** Finalised At */
            finalised_at: string;
        };
        /** DnaElementResponse */
        DnaElementResponse: {
            /**
             * Element Id
             * Format: uuid
             */
            element_id: string;
            /** Category */
            category: string;
            /** Statement */
            statement: string;
            /** Decay Class */
            decay_class: string;
            /** Origin */
            origin: string;
        };
        /** DnaResponse */
        DnaResponse: {
            /**
             * Dna Id
             * Format: uuid
             */
            dna_id: string;
            /** Version */
            version: number;
            /** Endorsed */
            endorsed: boolean;
            /** Elements */
            elements: components["schemas"]["DnaElementResponse"][];
            /** Changelog */
            changelog: components["schemas"]["ChangelogEntryResponse"][];
            /** Proposals */
            proposals: components["schemas"]["ProposalSummaryResponse"][];
        };
        /** DraftEditRequest */
        DraftEditRequest: {
            /** Body */
            body: string;
        };
        /** DraftResponse */
        DraftResponse: {
            /** Body */
            body: string | null;
            /** Problems */
            problems: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** InterviewStateResponse */
        InterviewStateResponse: {
            /** Question Key */
            question_key: string | null;
            /** Prompt */
            prompt: string | null;
            /** One Per Line */
            one_per_line: boolean;
            /** Answered */
            answered: number;
            /** Total */
            total: number;
            /** Completed */
            completed: boolean;
            /** Dna Created */
            dna_created: boolean;
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["MeUser"];
            workspace: components["schemas"]["MeWorkspace"];
        };
        /** MeUser */
        MeUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string | null;
            role: components["schemas"]["WorkspaceRole"];
        };
        /** MeWorkspace */
        MeWorkspace: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * OutcomeKind
         * @description The C7 vocabulary (Doc 03): contacted → replied → meeting → won/lost/
         *     disqualified.
         * @enum {string}
         */
        OutcomeKind: "contacted" | "replied" | "meeting" | "won" | "lost" | "disqualified";
        /** OutcomeRequest */
        OutcomeRequest: {
            kind: components["schemas"]["OutcomeKind"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason?: string | null;
        };
        /** OutcomeResponse */
        OutcomeResponse: {
            /**
             * Outcome Id
             * Format: uuid
             */
            outcome_id: string;
            kind: components["schemas"]["OutcomeKind"];
            /** Reinforced Statements */
            reinforced_statements: string[];
        };
        /** ProposalDecisionRequest */
        ProposalDecisionRequest: {
            /** Endorse */
            endorse: boolean;
        };
        /** ProposalResponse */
        ProposalResponse: {
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /** Statement */
            statement: string;
            /** Rationale */
            rationale: string;
            status: components["schemas"]["ProposalStatus"];
        };
        /**
         * ProposalStatus
         * @enum {string}
         */
        ProposalStatus: "proposed" | "endorsed" | "declined";
        /** ProposalSummaryResponse */
        ProposalSummaryResponse: {
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /** Statement */
            statement: string;
            /** Rationale */
            rationale: string;
            /** Status */
            status: string;
        };
        /** QueueItemResponse */
        QueueItemResponse: {
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
            /**
             * Prospect Id
             * Format: uuid
             */
            prospect_id: string;
            /** Business Name */
            business_name: string;
            polarity: components["schemas"]["RecommendationPolarity"];
            /** Rank */
            rank: number | null;
            /** Confidence Word */
            confidence_word: string;
            /** Components */
            components: components["schemas"]["ScoreComponentResponse"][];
            /** Rank Reason */
            rank_reason: string | null;
            /** Exclusion Reason */
            exclusion_reason: string | null;
            /** Has Brief */
            has_brief: boolean;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Week Key */
            week_key: string;
            /** Items */
            items: components["schemas"]["QueueItemResponse"][];
        };
        /** ReceiptResponse */
        ReceiptResponse: {
            /** Number */
            number: number;
            /** Claim */
            claim: string;
            /** Evidence Type */
            evidence_type: string;
            /** Observed At */
            observed_at: string;
        };
        /**
         * RecommendationPolarity
         * @enum {string}
         */
        RecommendationPolarity: "recommended" | "excluded";
        /** ScoreComponentResponse */
        ScoreComponentResponse: {
            /** Dna Statement */
            dna_statement: string;
            /** Signal Name */
            signal_name: string;
            /** Signal Family */
            signal_family: string;
            /** Supporting Evidence Ids */
            supporting_evidence_ids: string[];
            /** Contribution */
            contribution: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkspaceRole
         * @enum {string}
         */
        WorkspaceRole: "owner" | "member";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    get_queue_v1_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
        };
    };
    record_decision_v1_recommendations__recommendation_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_correction_v1_corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_outcome_v1_prospects__prospect_id__outcomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_v1_dna_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"][];
                };
            };
        };
    };
    decide_proposal_v1_dna_proposals__proposal_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_delivered_brief_v1_prospects__prospect_id__brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveredBriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_state_v1_interview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewStateResponse"];
                };
            };
        };
    };
    record_interview_answer_v1_interview_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dna_v1_dna_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnaResponse"];
                };
            };
        };
    };
    endorse_dna_v1_dna_endorse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnaResponse"];
                };
            };
        };
    };
    export_dna_document_v1_dna_document_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_brief_pdf_v1_prospects__prospect_id__brief_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_prospects_csv_v1_prospects_export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_billing_v1_billing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingResponse"];
                };
            };
        };
    };
    get_draft_v1_prospects__prospect_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_draft_v1_prospects__prospect_id__draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compose_draft_v1_prospects__prospect_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
